use Mix.Config

config :iugu,
  customers: [
    :id,
    :email,
    :name,
    :notes,
    :city,
    :cpf_cnpj,
    :cc_emails,
    :zip_code,
    :number,
    :complement,
    :default_payment_method_id,
    :proxy_payments_from_customer_id,
    :state,
    :district,
    :street,
    :custom_variables,
    :created_at,
    :updated_at
  ],
  subscriptions: [
    :id,
    :active,
    :created_at,
    :credits,
    :credits_based,
    :credits_cycle,
    :credits_min,
    :currency,
    :customer_email,
    :customer_id,
    :customer_name,
    :customer_ref,
    :cycled_at,
    :expires_at,
    :features,
    :in_trial,
    :logs,
    :plan_identifier,
    :plan_name,
    :plan_ref,
    :price_cents,
    :recent_invoices,
    :subitems,
    :suspended,
    :updated_at
  ]

